# gcloud builds submit --config infra/cloudbuild.yaml --substitutions=_TAG=v1 .
steps:
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-f", "backend/Dockerfile", "-t", "asia-northeast3-docker.pkg.dev/$PROJECT_ID/woori/api:${_TAG}", "."]
images:
  - asia-northeast3-docker.pkg.dev/$PROJECT_ID/woori/api:${_TAG}
substitutions:
  _TAG: latest
